receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
exporters:
  logging:
    loglevel: debug
  dynatrace:
    ## If no OneAgent is running on the host, endpoint and api_token need to be set
    ## Dynatrace Metrics Ingest v2 endpoint to receive metrics
    endpoint: "https://{your-environment-id}.live.dynatrace.com/api/v2/metrics/ingest"

    ## API token is required if an endpoint is specified and should be restricted to the 'Ingest metrics' scope
    ## hard-coded for illustration only, should be read from a secure source
    api_token: "your API token here"

    ## optional - prefix will be prepended to each metric name in prefix.name format
    prefix: my_app
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging, dynatrace]